### PR TITLE
Qss sara

### PR DESCRIPTION
**Pull request by pluflou**
Main new test module that includes all tests is `tests/solardatatools/test_signal_decompositions.py`. Files for i/o data for tests and for generating them are in `tests/fixtures/signal_decompositions`.

The module `solardatatools/signal_decompositions.py` is still a work in progress.

### CODE REVIEW

**Comment by bmeyers** [comment]
Hi @pluflou, is this ready for review and merging now? Or do you have more to add to the PR?

**Comment by pluflou** [comment]
@bmeyers Still have to add the signal decomposition module after refactoring to remove obsolete functionalities.

**Comment by pluflou** [comment]
@bmeyers this is ready for review and merging now.

**Comment by pluflou** [comment]
@bmeyers just kidding, looks like there is a bug I missed. Not ready yet.

**Comment by pluflou** [comment]
@bmeyers ok looks good now!

**Comment by bmeyers** [comment]
@Thistleman Can you advise as to why our GitHub CI/CD pipeline isn't being run on this PR?

**Pull request closed without merging**
