### PR TITLE
New development work

### PR DESCRIPTION
**Pull request by bmeyers**
Switch to `CLARABEL` solver for convex problems.

### CODE REVIEW

**Comment by bmeyers** [comment]
@malikmayank all others who might review this are out today, so if you can give it your quick review, that would be helpful!

**Review by malikmayank — APPROVED** [review]
python syntax looks good.

**Review by malikmayank — APPROVED** [review]
syntax looks good here as well

**Comment by bmeyers** [comment]
thanks @malikmayank!

**Comment by bmeyers** [comment]
two tests are still failing during on the CI/CD server, and on my local machine. Unfortunately, they are not the same two tests! 😮‍💨 


Screenshot 2023-09-26 at 10 37 24 AM
Screenshot 2023-09-26 at 10 37 34 AM

**Comment by bmeyers** [comment]
Screenshot 2023-09-26 at 10 37 34 AM

**Comment by bmeyers** [comment]
Okay, time to start spamming `print` statements into the tests that are failing on the VM 🙃

**Pull request merged**
